### ISSUE TITLE
Migrate AddonManager to use .ui files instead of generating them from within the script

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-addons#100]
Currently the dialog windows code is generated within the python files. Separating this code out in to .ui files would make it easier to translate and refine the AddonManager.

**Comment by luzpaz** [comment]
@easyw perhaps you have a moment to also work on this (based on your experience with https://github.com/easyw/Manipulator/issues/14)?

**Comment by chennes** [comment]
The UI for the Addon Manager has been more or less completely re-written since this bug post. Strings are all translatable, whether from a UI file or in Python.
