### ISSUE TITLE
When adding a macro give option to auto tie it to a custom toolbar

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-addons#107]
Ref: https://forum.freecadweb.org/viewtopic.php?f=8&t=31872#p265149

**Comment by chennes** [comment]
This is in progress now: the first step is https://github.com/FreeCAD/FreeCAD/pull/5501

**Comment by chennes** [comment]
Final PR: https://github.com/FreeCAD/FreeCAD/pull/6408

**Comment by chennes** [comment]
Merged as of 75d2233ed6cf29b3a618e50475b830b37ef42361
