### ISSUE TITLE
SlopedPlanes repo is missing

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-addons#111]
https://github.com/caceres/SlopedPlanesMacro/

CC @caceres

**Comment by caceres** [comment]
My FreeCAD user account has been cancelled. I understand it like unfriendly action. In consequence, and by security reasons, the GitHub account has been frozen.

**Comment by yorikvanhavre** [comment]
What FreeCAD user account? On the forum??

**Comment by luzpaz** [comment]
@luzpaz he has no github activity history
Checkout: https://github.com/caceres

**Comment by yorikvanhavre** [comment]
This is strange, AFAIK we never cancelled any account on the forum (apart from banning spam bots, of course)

**Comment by luzpaz** [comment]
Wait, i'm confused. Why are we talking about the forum? User @caceres has no github history. He said:

> My FreeCAD user account has been cancelled. I understand it like unfriendly action. In consequence, and by security reasons, the GitHub account has been frozen.

The question is, what happened ?

What about the integrity of the SlopedPlanes code, is there something we need to know ?

**Comment by caceres** [comment]
the code is guaranteed in my computers, the users' computers, and gitlab.
If someone is confused, the caution is the procedure

**Comment by luzpaz** [comment]
> If someone is confused, the caution is the procedure

Sorry, not sure what you mean by `the caution is the procedure`

Again, the question: why was the account canceled?

**Comment by caceres** [comment]
The account (I'm referring to my github account) was cleaned by security reasons. I don't know what is happening with my forum account and I will be extremely careful. 
And this was explained previously.
@luzpaz, I'll be thankful with less mail in my server.
The administrators will resolve. Until then, I'm not too much speaker.

**Comment by yorikvanhavre** [comment]
Ok SlopedPlanes was removed.. If you have it hosted somewhere else, I'll be happy to add it again
