### ISSUE TITLE
Request for adding Reporting Workbench

### ISSUE THREAD

**Issue by furti** [FreeCAD/FreeCAD-addons#116]
Would be nice when the Reporting Workbench gets added to the addon Manager. Forum Post ist this https://forum.freecadweb.org/viewtopic.php?f=9&t=33403

- [x] Add some screenshots to the README.md
- [x]  Add the word FreeCAD in the repo description
- [x] Optional screencast showing the gist of the workbench: There is a "Getting started" guide with pictures in the Readme. Will update the Installation instruction when the workbench is available via the addon Manager.
- [x] Tag your repo as 'freecad'
- [x] What 3rd party dependencies does your WB require ? No dependencies required 
- [x] Mention the FC forum thread that your users can post to for support in the README.md

**Comment by yorikvanhavre** [comment]
Done!
