### ISSUE TITLE
Addon manager window larger than screen

### ISSUE THREAD

**Issue by kisolre** [FreeCAD/FreeCAD-addons#119]
Whe upgrading addons upon the operation completion Addon manager window displays several lines of the git log. Resizing the window in this state could make the window bigger than screen.
Forum thread: [url](https://forum.freecadweb.org/viewtopic.php?f=3&t=34788)

OS: Windows 8.1
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16078 (Git)
Build type: Release
Branch: master
Hash: 67df9f3a828fbb0fec29d039792d4baf3d9ee8e0
Python version: 3.6.6
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: Bulgarian/Bulgaria (bg_BG)

**Comment by luzpaz** [comment]
https://forum.freecadweb.org/viewtopic.php?f=3&t=34788&p=330433#p330433

**Comment by luzpaz** [comment]
Per the forum, this is not an issue on 0.19 and therefore we can close this ticket, right?
