### ISSUE TITLE
If any dimension command is activated and escaped using escape, the dimensioning skeleton translates to the right and bottom

### ISSUE THREAD

**Issue by QuantumNovice** [FreeCAD/FreeCAD-addons#134]
If any dimension command is activated and escaped using escape, the dimensioning skeleton translates to the right and bottom.

![image](https://user-images.githubusercontent.com/43876848/60387335-e6e6f100-9aba-11e9-89e8-7ae3fcf68e7c.png)

**Comment by luzpaz** [comment]
Please open a FreeCAD forum thread. This issue queue is only related to Addon Manager specific issues. Also, note that Drawing Dimensioning WB is obsolete and has been replaced the TechDraw.
