### ISSUE TITLE
Feature: Addon Manager search bar (quickly find addon/workbench)

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-addons#139]
FreeCAD Addons is growing. It may be time to add a little search bar to the Addon Manager to quickly filter through the list of addons to find ones specific addon

**Comment by chennes** [comment]
This is done as of https://github.com/FreeCAD/FreeCAD/commit/acfde1a4b655cee307e3a8fc0066ca5c1dc2fdc9
