### ISSUE TITLE
Time to remove addons_installer.FCMacro ?

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-addons#141]
https://github.com/FreeCAD/FreeCAD-addons/blob/master/addons_installer.FCMacro  
Do we still need it?

**Comment by sgrogan** [comment]
I would vote to remove it. If someone really needs it they can still checkout a previous commit where it still existed.

**Comment by luzpaz** [comment]
Example of why we should remove it: https://forum.freecadweb.org/viewtopic.php?f=22&t=37966#p323126
