### ISSUE TITLE
"addons_installer.FCMacro" file link "404 not found" error

### ISSUE THREAD

**Issue by MantaRayDeeJay** [FreeCAD/FreeCAD-addons#148]
Hello,
I would like to download the "addons_installer.FCMacro" file but it seems that there is a "404 not found" error.

![Capture d’écran (22)](https://user-images.githubusercontent.com/20164048/63257868-fe508800-c27a-11e9-8dac-079050dbe6e1.png)

**Comment by luzpaz** [comment]
What for? It's deprecated.  
See https://github.com/FreeCAD/FreeCAD-addons/issues/141

**Comment by luzpaz** [comment]
Unless you're using an inferior version of FreeCAD, we recommend using the built-in Addon Manager to download workbenches and macros. Nonetheless, the link tot he deprecated macro is now fixed.  
Closing ticket

**Comment by MantaRayDeeJay** [comment]
I'm always using the v0.16 of FreeCAD because I can use it on a Windows XP Light Weight VM guest.
