### ISSUE TITLE
Installed with Auto installler but wont show workbench

### ISSUE THREAD

**Issue by Ddawg747** [FreeCAD/FreeCAD-addons#15]
i have tried manual install and still i get the same error message which is as follows...

During initialization the error DLL load failed: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail. occurred in C:\Users\Dillan\AppData\Roaming\FreeCAD\Macro\Mod\assembly2\InitGui.py

even after many trials with the auto installer i still get the exact same error.

**Comment by yorikvanhavre** [comment]
This is apparently a problem in the assembly2 workbench and not in this macro. I suggest you report the issue directly on the assembly2 project page instead of here...
