### ISSUE TITLE
Import cadquery , FrreeCAD Error ?

### ISSUE THREAD

**Issue by selvakarna** [FreeCAD/FreeCAD-addons#154]
I got following error when i import cadquery package, this package are installed but i got error bellow,

>>> import freecad
>>> import cadquery
Traceback (most recent call last):
  File "/home/hp/.local/lib/python3.6/site-packages/cadquery/freecad_impl/__init__.py", line 151, in <module>
    import FreeCAD
ModuleNotFoundError: No module named 'FreeCAD'

During handling of the above exception, another exception occurred:

   import FreeCAD
ImportError: dynamic module does not define module export function (PyInit_FreeCAD)

**Comment by luzpaz** [comment]
Not the place to open tickets about individual addons. Best to do so by starting a thread on the FreeCAD forum.
