### ISSUE TITLE
[FEATURE] Ability to access FreeCAD Addons Manager from the CLI (w/o GUI)

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-addons#156]
Run FreeCAD from the CLI with a flags that can:
* List all addons/macros
* Update pre-existing addons/macros
* Install addons/macros
* Remove addons/macros

Ref:   
* https://forum.freecadweb.org/viewtopic.php?f=8&t=40297
* https://forum.freecadweb.org/viewtopic.php?f=22&t=40299

**Comment by mmiscool** [comment]
This one has my vote.

**Comment by chennes** [comment]
Seer the documentation of the new API here: https://wiki.freecadweb.org/Std_AddonMgr#Addon_Manager_API
