### ISSUE TITLE
[FEATURE] Ask Addon Authors to use LGTM CI analysis

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-addons#163]
**Is your feature request related to a problem? Please describe.**  
Standardizing code quality in all Addons 

**Describe the solution you'd like**  
Using [LGTM](https://www.freecadweb.org/wiki/LGTM) 

**Additional context**  
Asking Authors to add a `.lgtm.yml` file and sign up for their free service to run a check on their specific Addon repo so it generates a report of issues to be fixed.  

- [ ] 3D_Printing_Tools
- [x] A2plus
- [x] [AirPlaneDesign](https://github.com/FredsFactory/FreeCAD_AirPlaneDesign)
- [ ] animation
- [ ] ArchTextures
- [ ] assembly2
- [x] Assembly4
- [ ] Autoload
- [ ] BCFPlugin
- [ ] BIM
- [ ] BIMBots
- [x] BOLTSFC
- [ ] CADExchanger
- [ ] cadquery_module
- [ ] Cfd
- [x] CfdOF
- [ ] CommandPanel
- [ ] CubeMenu
- [ ] cura_engine
- [ ] [CurvedShapes](https://github.com/chbergmann/CurvedShapesWorkbench/issues/8)
- [x] [Curves](https://github.com/tomate44/CurvesWB/pull/24)
- [x] [Defeaturing](https://github.com/easyw/Defeaturing_WB/pull/3)
- [ ] DesignSPHysics
- [ ] dodo
- [ ] drawing_dimensioning
- [ ] dxf_library
- [ ] DynamicData
- [x] [EM](https://github.com/ediloren/EM-Workbench-for-FreeCAD/pull/4)
- [ ] ExplodedAssembly
- [x] fasteners
- [x] FCGear
- [ ] flamingo
- [ ] frame
- [ ] GDML
- [ ] GDT
- [ ] geodata
- [ ] Geomatics
- [ ] Glass
- [ ] icons
- [ ] IconThemes
- [ ] InventorLoader
- [ ] kerkythea
- [ ] kicadStepUpMod
- [x] [lattice2](https://github.com/DeepSOIC/Lattice2/pull/38)
- [ ] Launcher
- [ ] LCInterlocking
- [ ] Lithophane
- [ ] Manipulator
- [ ] MeshRemodel
- [ ] MOOC
- [ ] NavigationIndicator
- [ ] nurbs
- [ ] Part-o-magic
- [ ] parts_library
- [ ] pcb
- [ ] persistenttoolbars
- [ ] PieMenu
- [ ] Plot
- [ ] pluginloader
- [ ] pyrate
- [ ] reconstruction
- [x] Reinforcement
- [ ] RemBench
- [ ] Render
- [ ] Reporting
- [ ] ~retr3d~
- [ ] SelectorToolbar
- [x] [sheetmetal](https://github.com/shaise/FreeCAD_SheetMetal/pull/111)
- [ ] Ship
- [ ] ShortCuts
- [ ] Silk
- [ ] slic3r-tools
- [ ] SlopedPlanesMacro
- [ ] symbols_library
- [ ] TabBar
- [ ] ThreadProfile
- [ ] timber
- [ ] ToolbarStyle
- [ ] WebTools
- [ ] workfeature
- [ ] workfeature-macro
- [ ] yaml-workspace

**Comment by luzpaz** [comment]
Related ticket: https://github.com/FreeCAD/FreeCAD-macros/issues/73

**Comment by Thovthe** [comment]
Deafeaturing should get a checkmark.

**Comment by luzpaz** [comment]
LGTM has now been sunset as a service: https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/
