### ISSUE TITLE
Addon Manager freezes when reading wiki

### ISSUE THREAD

**Issue by uTMY** [FreeCAD/FreeCAD-addons#173]
Addon manager freezes when attempting to read past this addon

SlopedPlanesMacro @ 9475f68
Changed SlopedPlanesMacro url to gitlab repo

when it reaches this addon,  the gui hangs and does not display the list of addons.

OpenSuse Leap 15.1 - FreeCAD version 0.18

**Comment by luzpaz** [comment]
can you recreate now?

**Comment by uTMY** [comment]
Hi Luzpaz

That now works perfectly,  whatever you did fixed it.

Many thanks
uTMY

**Comment by luzpaz** [comment]
Thanks for reporting.
