### ISSUE TITLE
[Formating]

### ISSUE THREAD

**Issue by berndhahnebach** [FreeCAD/FreeCAD-addons#179]
how about sorting the submodules in .gitmodules by ABC?

**Comment by luzpaz** [comment]
I'm using vscode but I can't seem to find a 'sort by parent' option.  
any idea how to do this automagically?

**Comment by luzpaz** [comment]
Ok, found a solution:
`parallel -L3 -ka .gitmodules echo | sort -n | perl -pe 's/]/]\n/' | perl -pe 's/\s+(url.*)/\n\t\1/g'`
