### ISSUE TITLE
[FEATURE] Feed and speeds Calculator

### ISSUE THREAD

**Issue by Supermagnum** [FreeCAD/FreeCAD-addons#186]
Feeds and Speeds Calculator , it should include:
Import and Export tables from CSV files, use Manufacturer’s Recommended Data, define tool geometry, and use tool types for Mills, Routers (special router cutters handled) and Lathes. End Mill Speed and Feed: Coatings (including PCD) & Geometry (Ballnose, Upcut, Downcut, Compression, and more).
Drill Feeds and Speeds: Carbide, HSS, and Parabolic Turning and Lathe Tools Reamers, Saws, Woodruff Cutters, Corner Rounders, Tapping, Thread Mills, and Boring Heads.

Material Database:
Metals of all kinds, plastics, composites, even hard to find materials like Tungsten, Cobalt Chrome, and Graphite.

**Comment by luzpaz** [comment]
Not the place for feature requests regarding individual workbenches.This is strictly for Addon Manager and managing addons in general. What you're looking for is the [Path subforum](https://forum.freecadweb.org/viewforum.php?f=15)
Make sure to search those topics first as you are not the first that has requested them. Good luck
