### ISSUE TITLE
Rhino3D addon

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-addons#19]
https://github.com/KeithSloan/FreeCAD_ImportNurbs
This is still in development. Just wanted to bring your attention to it.

**Comment by yorikvanhavre** [comment]
This contains c++ code, so it cannot be an addon... It would need to be added to the FreeCAD source code. But letś leave this open to keep an eye on it

**Comment by chennes** [comment]
This is now an official AddOn, so I believe this "watch" can be closed.
