### ISSUE TITLE
[Bug] Chinese local users reporting that 0.19.1 Addon Manager is not displaying any addons

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-addons#190]
**Describe the bug**  
Chinese locale users have malfunctioning Addon Manager that doesn't display any addons  
Thread (in chinese): https://forum.freecadweb.org/viewtopic.php?f=40&t=55532

**To Reproduce**  
(To be translated)

**Expected behavior**  
Addon manager displays addons

**Screenshots**  
![image](https://user-images.githubusercontent.com/4140247/116781977-79100580-aa54-11eb-991b-6d3749e857b3.png)

**Desktop (please complete the following information):**

![image](https://user-images.githubusercontent.com/4140247/116781990-8af1a880-aa54-11eb-8e17-d435b1694271.png)

**Additional context**  
Possible unicode issue I imagine.

**Comment by SilentCA** [comment]
It may be the network problem. 
Check whether you can access "https://raw.githubusercontent.com/FreeCAD/FreeCAD-addons/master/addonflags.json", where FreeCAD gets addon list.
I fixed the network problem by editing hosts file, then FreeCAD works fine.

**Comment by hughchin95** [comment]
you are right,I can not link this  website .  I am trying to use VPN to solve  it.  I will come  back here if I succeed.

**Comment by hughchin95** [comment]
I solved it by add hosts of github.com to C:\Windows\System32\drivers\etc\hosts

**Comment by chennes** [comment]
This then looks like a local DNS issue, right? Can we close?
