### ISSUE TITLE
[FEATURE] Installed Addons version info could be added to the FreeCAD Help > About dialog

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-addons#199]
**Is your feature request related to a problem? Please describe.**  
Addon authors and users suffer a disconnect in regard to the version of the Addon they may be using when they report issues for troubleshooting.

**Describe the solution you'd like**
A section in the About dialog showing all addons installed and their respective versions. This should be more attainable now with Preference packs thanks to @chennes  

**Describe alternatives you've considered**
Adding the version info to the workbench name that is visible in the workbench drop-down menu.

**Additional context**
I don't have a proposal for a mockup. But I'm sure we could engineer the About dialog a little more spatially efficient (columns?)

**Comment by chennes** [comment]
This should be straightforward for macros (which normally have version info embedded) and Addons that have a package.xml file. For Addons that have not yet added this new metadata file, there isn't a clear way of achieving this.
