### ISSUE TITLE
Geometric dimensioning and tolerancing for 3D (WIP)

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-addons#20]
https://github.com/jlguardi/FreeCAD_GDT
See https://github.com/jlguardi/FreeCAD_GDT/issues/1#issuecomment-278939381

**Comment by yorikvanhavre** [comment]
Not finished enough to be added here I think, but let's keep this open to keep an eye on it

**Comment by luzpaz** [comment]
Added to repo. Thanks!
Closing
