### ISSUE TITLE
[FEATURE] Check if there are updates for 3rd party workbench (even if Addon Manager is not invoked)

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-addons#206]
Original ticket: https://tracker.freecadweb.org/view.php?id=2993  
Original thread: https://forum.freecadweb.org/viewtopic.php?f=3&t=21565&p=167959#p167777

**Comment by chennes** [comment]
See also #95

**Comment by chennes** [comment]
Closing in favor of https://github.com/FreeCAD/FreeCAD/issues/12970
