### ISSUE TITLE
DesignSPHysics

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-addons#21]
https://github.com/ndrs92/DesignSPHysics/issues/2

**Comment by yorikvanhavre** [comment]
The author doesn't seem ready to add his work here, let's wait until he says so.

**Comment by ndrs92** [comment]
Hi there!

I changed a bit of the structure of the code to match https://github.com/ndrs92/DesignSPHysics/issues/2 

The DesignSPHysics.FCMacro file loads a 'DesignSPHysics' module that is meant to be placed in the Mod directory of FreeCAD's install folder.

You can add DesignSPHysics here when you want. Notify me if more changes are needed to be made.

I'm going to update the standalone installer to copy the code following the new way and update the documentation to match the new manual install procedure.

When the work is added I'll also incorporate this way of installing.

Thanks for your work!

**Comment by yorikvanhavre** [comment]
Hi Andrés,
Actually what happens in FreeCAD is that all folders found in Mod are added to the sys.path. So the DesignSPHysics folder will already be part of sys.path. So "import DesignSPHysics" will not work.
The simplest way maybe is to rename your __init__.py to something else, for ex DesignSPHysics.py. Then "import DesignSPHysics" will import that file, not the folder. But that might be confusing, maybe better to use another name.
I agree this system is not very "pythonic", there are ongoing discussions to make that better...

**Comment by ndrs92** [comment]
Oh! I understand. It works for me because some time in the past I manually added a bunch of FreeCAD dirs to my path.

Anyway, tomorrow in work hours I'll rename the main Python file and test with a clean VM. Thanks for the help.

**Comment by ndrs92** [comment]
Hi, I updated the project structure and the installer to match the way you described.

So now in the Mod folder there is a DesignSPHysics folder with a DesignSPHysics.py file inside. 

In the other hand the DesignSPHysics.FCMacro continues to be into the Macro folder. This way, in a Vanilla ubuntu machine works perfectly.

I hope it is ready to add it now. Thank you so much.

**Comment by yorikvanhavre** [comment]
Ok everything looks good! I'm adding it. Thanks for adapting your code!

**Comment by yorikvanhavre** [comment]
9ae872e7e
