### ISSUE TITLE
[FEATURE] 'Add custom repository' button in the Addon Manager that links to Preferences -> Addon Manager -> Addon Manager preferences

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-addons#213]
**Is your feature request related to a problem? Please describe.**
Just a UX convenience  

**Describe the solution you'd like**
![Screenshot_20220417_181659](https://user-images.githubusercontent.com/4140247/163734294-1902b3f1-9903-4f22-a033-fad51c3cd72a.png)
which opens the Preferences -> Addon Manager -> Addon Manager preferences
 
![Screenshot_20220417_182030](https://user-images.githubusercontent.com/4140247/163734325-99361ba6-c2c4-470f-8fab-ec79cb1de27f.png)

**Describe alternatives you've considered**
Some static text to orient the user. But a button seems smarter.

**Additional context**
Not sure if there are technical issues with this for example, does addon manager dialog need to be closed in order to open the 'Addon Manager preferences' and to then see the changes made to the preferences?

**Comment by chennes** [comment]
I'm about at the limit of the number of buttons I can comfortably cram down in the lower left corner, and your technical concern is right -- the Addon Manager reads its preferences only when it is launched, not continuously while it is running, so the Addon Manager would have to restart when the preferences changed. I'm not sure I see any great advantage to adding this button considering the difficulty on the technical side.

**Comment by luzpaz** [comment]
Yea, closing.
