### ISSUE TITLE
[Bug] Addon Manager browser window not displaying at all

### ISSUE THREAD

**Issue by sslupsky** [FreeCAD/FreeCAD-addons#216]
**Describe the bug**
Addon manager does not refresh when running latest 0.20

**To Reproduce**
1. Tools->Addon manager
2. Select any addon in the list (example below I selected kicadstepup and 3D printing tools )
3. Window is empty

![Screen Shot 2022-04-28 at 11 28 43 AM](https://user-images.githubusercontent.com/16888734/165812708-64de2e8d-0e8b-40c1-bba1-2cda3596d830.png)

![Screen Shot 2022-04-28 at 11 28 10 AM](https://user-images.githubusercontent.com/16888734/165813105-fc1d3a0e-9197-4e7b-a81b-3a38e0eed043.png)

**Expected behavior**
Window should display git info

**Desktop (please complete the following information):**
```
OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 0.20.28765 (Git)
Build type: Release
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: C/Default (C)
Installed mods: 
  * kicadStepUpMod 10.10.4
```

**Comment by luzpaz** [comment]
Hey @ipatch, do you mind trying to reproduce on macOS (HEAD) ?

**Comment by ipatch** [comment]
yeah it'll take me a few.

@sslupsky are you launching freecad from cli or are using a `FreeCAD.app` bundle?

if building from source, please produce commands to replicate build, please and thank you. 🙏

**Comment by sslupsky** [comment]
@ipatch I launched the app bundle.  I downloaded the latest nightly (weekly?) build of 0.20 earlier today (28765)

**Comment by sslupsky** [comment]
My previous install of 0.20 (build 27078) works fine.

**Comment by ipatch** [comment]
@sslupsky 

it seems you're using the conda release

https://github.com/FreeCAD/FreeCAD-Bundle/releases/download/weekly-builds/FreeCAD_weekly-builds-28765-OSX-x86_64-conda.dmg

ill have to check and see if i exp the same issue if i build a bundle using cmake with homebrew provided packages

**Comment by chennes** [comment]
I have received no further reports of this behavior -- if it reappears it is a packaging issue that we'll have to address in the specific executable that is being used.
