### ISSUE TITLE
Add `capytaine` as an external dependency for ShipWB in to ALLOWED_PYTHON_PACKAGES.txt

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-addons#217]
@chennes noted that there was a complication with installing capytaine. This ticket's function is to resolve both issues (adding to `ALLOWED_PYTHON_PACKAGES.txt` and making an upstream ticket in the capytaine repo if necessary). 

_Originally posted by @sanguinariojoe in https://github.com/FreeCAD/FreeCAD/issues/6764#issuecomment-1113209586_

**Comment by sanguinariojoe** [comment]
Just for the record, capytaine is installing fine on my Linux-Manjaro system

**Comment by luzpaz** [comment]
@chennes what was the issue you encountered? Do you mind elaborating?
