### ISSUE TITLE
fatal: No url found for submodule path 'FCGear' in .gitmodules

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-addons#225]
Trying to do a repo update, i encounter this error when running this one liner (it avoids checking out submodules who's default branch is not 'master')

```shell
git submodule foreach 'case $name in MnesarcoUtils|SlopedPlanesMacro|Design456|OpticsWorkbench|Beltrami|Trails|SearchBar|AnimationFreeCAD) ;; *) git checkout master ;; esac'
```

Does this error have to do with afd5107f8eafbd4c046e72c855372026abb76e9e ?

**Comment by chennes** [comment]
I don't know - the Addon Manager doesn't use the submodules feature of git, it just parses the .gitmodules file. I don't know what git does if the file changes and it already has those submodules checked out.

**Comment by luzpaz** [comment]
This is still a problem. Have not been able to update the submodules since the .gitmodules file was altered in https://github.com/FreeCAD/FreeCAD-addons/commit/afd5107f8eafbd4c046e72c855372026abb76e9e
