### ISSUE TITLE
[New Stylesheet] ExtremeProDark

### ISSUE THREAD

**Issue by MisterMakerNL** [FreeCAD/FreeCAD-addons#226]
It's just a style-sheet no need for a lot of text for explaining [link](https://github.com/MisterMakerNL/ExtremeProDark), its a in my opinion better version of the prodark.
Also the pro dark dev doesn't seem to react anymore or update his code.
https://github.com/MisterMakerNL/ExtremeProDark

**Comment by luzpaz** [comment]
Doesn't have a package.xml file: https://wiki.freecadweb.org/Package_Metadata

**Comment by MisterMakerNL** [comment]
@luzpaz I added it!

**Comment by luzpaz** [comment]
Nice, giving props to @turn211 and @studiopetrikas :wink:

**Comment by luzpaz** [comment]
@MisterMakerNL this stylesheet works on master, correct?

**Comment by Chrismettal** [comment]
Don't we need to package it as a complete PreferencePack to provide it via the addon manager? 
The original [ProDark](https://github.com/turn211/ProDarkThemePreferencePack) follows the packaging format as well and I don't see a reason to stray from the norm here. In the past stylesheets were included in FreeCADs source directly, and now we supply them via the addon manager as PreferencePacks.

See also the [guide to PreferencePack structure](https://wiki.freecadweb.org/Preference_Packs#Preference_Pack_structure)

**Comment by MisterMakerNL** [comment]
I just copied it from pro-dark. :)

**Comment by Chrismettal** [comment]
Can you make sure your pack conforms to the structure specified completely, and then try to manually install your pack with the addon manager in the same way as described here, by manually adding your packs repo as an addon source:

https://github.com/dracula/freecad/issues/2#issuecomment-1179737161

If that works, you can open up a PR to this repo, adding your pack, and testers can try your pack out the same way before merging.

**Comment by luzpaz** [comment]
Closing in favor of #229
