### ISSUE TITLE
Optical raytracer preview

### ISSUE THREAD

**Issue by joha2** [FreeCAD/FreeCAD-addons#25]
Optical raytracer preview workbench:
* setup demo system
* trace some rays (field sampling, ...)
* change some geometrical parameters of the surfaces
* define materials
* define surfaces
* define local coordinates

The given tree entry is just before we changed our core code fundamentally.
Now the FreeCAD workbench is also broken. But at the given point it should all still functional.

https://github.com/mess42/pyrate/tree/ec5aac433636659fc39226d270a6c6e544a2c313

**Comment by yorikvanhavre** [comment]
Added!
