### ISSUE TITLE
Deprecate freecad-slic3r-tools

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-addons#258]
https://github.com/limikael/freecad-slic3r-tools  

* Hasn't been hacked on since Jan 2020 
* No response in the issue queue (no response from @limikael)
* upstream slic3r project looks like they're struggling 
   * https://github.com/slic3r/Slic3r/issues/5158 
   * https://github.com/slic3r/Slic3r/commits/master

**Comment by limikael** [comment]
Hello, sorry for the radio silence... Yes I think the best thing is to retire it, unfortunately, I don't really have time to work on it at the moment...
