### ISSUE TITLE
[Bug] `pip install --user` no longer supported in debian trixie

### ISSUE THREAD

**Issue by khimaros** [FreeCAD/FreeCAD-addons#275]
**Describe the bug**
i believe https://github.com/realthunder/FreeCAD_assembly3/issues/1317 may actually be a more general issue with AddonManager, since i believe it is responsible for installing deps.

**To Reproduce**
1. install debian trixie (testing)
2. install the Assembly3 addon
3. open the workspace and select "Yes" to install py-slvs

**Expected behavior**
installation should succeed

**Desktop (please complete the following information):**
 - OS: debian trixie
 - FreeCAD Version: 0.20.2

**Comment by chennes** [comment]
Thanks for the report -- presumably the best solution is for FreeCAD to run its Python interpreter in a virtual environment (eliminating the need for the --user option).

**Comment by khimaros** [comment]
@chennes i believe that is the recommended approach now.

**Comment by chennes** [comment]
I'm going to close this issue, it's now a FreeCAD repo issue: https://github.com/FreeCAD/FreeCAD/issues/12202
