### ISSUE TITLE
[Bug] Add protobuf in ALLOWED_PYTHON_PACKAGES.txt

### ISSUE THREAD

**Issue by Taack** [FreeCAD/FreeCAD-addons#299]
Is it possible to allow protobuf dependency ? It should be portable and be 100 % pure Python. It eases C/C++/Java/C# data exchange.

Regards !

**Comment by luzpaz** [comment]
If @chennes is cool with it, then please proceed to make a PR. The appropriate file is at: https://github.com/FreeCAD/FreeCAD-addons/blob/master/ALLOWED_PYTHON_PACKAGES.txt

**Comment by Taack** [comment]
Done ! I made a pull request

[Update ALLOWED_PYTHON_PACKAGES.txt, add protobuf #313](https://github.com/FreeCAD/FreeCAD-addons/pull/313)
