### ISSUE TITLE
empty submodules directories

### ISSUE THREAD

**Issue by one-quaker** [FreeCAD/FreeCAD-addons#3]
Hi!
"git submodule foreach git pull" doesn't work, git version 2.5.0, ubuntu 15.10
git submodule init; git submodule update # works for me

**Comment by yorikvanhavre** [comment]
This procedure is actually not needed anymore since the introduction of the macro.

**Comment by luzpaz** [comment]
@yorikvanhavre what is this macro? I was asked in #90 to update the submodule link to an upstream workbench repo. How do I do this?
