### ISSUE TITLE
Add a short description of each current addon in the README

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-addons#32]
Currently it's difficult to understand in a brief way (without clicking on each addon repo) what's each addon does. It's possible to speculate by the addon name.
I propose we have a section in the README.md that explains what each current addon does. We can ask addon authors to also provide this if they'd like to add their addon to this repo.

**Comment by luzpaz** [comment]
PR submitted #34

**Comment by luzpaz** [comment]
@yorikvanhavre do you mind reviewing at your convenience ?

**Comment by yorikvanhavre** [comment]
Great! but, will you keep it updated? ;)

**Comment by yorikvanhavre** [comment]
It's merged
