### ISSUE TITLE
Pictures from readme not showing in the addon manager of FreeCAD 1.0

### ISSUE THREAD

**Issue by APEbbers** [FreeCAD/FreeCAD-addons#327]
I noticed that with the new FreeCAD 1.0, this is not shown properly. Probaly due to HTML syntaxes. It shows properly with FreeCAD 0.21, 
Have you noticed something like this? The issue persists even when all HTML is removed from the readme.

The pictures below are from the Ribbon UI addon. I had this issue earlier with the TitleBlock WB. Then some code was written to remove HTML. But I think the addon should show the readme as shown in github itself.

FC 1.0:
![image](https://github.com/user-attachments/assets/ca6fcc23-036a-4ffb-98a9-417d120b1fbd)

FC 0.21:
![image](https://github.com/user-attachments/assets/8779ae86-bef6-4540-87d2-80af817da8db)

**Comment by luzpaz** [comment]
Confirmed on:  
```
OS: Manjaro Linux (KDE/plasma/xcb)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39024 (Git) AppImage
Build type: Release
Branch: main
Hash: cf8ad6637351819dfa07d49cfd65d511fe14a084
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
```

**Comment by chennes** [comment]
Use relative paths in your image URLs (and yes, Qt's Markdown parser does not understand very much HTML, so your best bet is to use pure markdown in your README).

**Comment by luzpaz** [comment]
> Qt's Markdown parser does not understand very much HTML

It understands the collapsed div though right?

**Comment by chennes** [comment]
Basically, any HTML support is "at your own risk" -- Qt claims it supports "GitHub-flavored" Markdown, but in my experience you're far better off just keeping it as simple as possible.

**Comment by APEbbers** [comment]
I've removed the HTML and the information about other install options. Instead i've added a link to the wiki page "installation".
I've also changed the paths to relative paths:
![image](https://github.com/user-attachments/assets/c02c9010-5281-466e-9fb2-f52ebc77a21d)

is this the correct way? The pictures are still not showing

**Comment by hasecilu** [comment]
The only differences I see with other working READMEs is that you don't have text inside the brackets `[]`. 

I use: `![Example of some FreeGrid components](img/screen.png "Example of some FreeGrid components")`, The text between parentheses makes a tooltip to appear on GitHub.

**Comment by APEbbers** [comment]
Yes, that solved it! thanks for the help!
