### ISSUE TITLE
BOLTS does not work

### ISSUE THREAD

**Issue by berndhahnebach** [FreeCAD/FreeCAD-addons#38]
Hi Yorik, 

BOLTS does not work. See https://forum.freecadweb.org/viewtopic.php?f=8&t=4549&p=180700#p172208

the BOLTS package can not just copied. One needs to run some command to make a FreeCAD package out of BOLTS.  Refere to http://www.bolts-library.org/en/docs/0.3/general/utility-script.html for more information. 

Johannes has not been active for a long time (2 years on FreeCAD forum and 1 year on BOLTS github). I will get in touch with Johannes these days, but this may take some time. Sometimes it could be cumbersome to get in touch with people who have left a project.

I have set up a BOLTS backend for Allplan and fixed some FreeCAD related stuff. I even added new data. I do not want to see BOLTS dying. On https://github.com/berndhahnebach/BOLTS/commits/boltsdev you can see my latest development in this regard. 

I made a FreeCAD package out of my latest development. On https://github.com/berndhahnebach/BOLTSFC I have set up a repository which only contains the BOLTS FreeCAD package. Means this data (the FreeCAD macro file and the directory BOLTS) have to be copied to the FreeCAD macro folder and BOLTS should run smooth. At least it does on my FreeCAD. You may could add this to the AddOn manager as long as we do not have any better.

cheers bernd

**Comment by yorikvanhavre** [comment]
Hm I had forgotten that BOLTS needs to be built.
I'll have a look if it is possible to make the addons manager build it after installing, otherwise we can use your repo instead, maybe.

**Comment by berndhahnebach** [comment]
How about this? Jahannes has not aswered on my mails.  :-(   Should we temporary use my repo? I will not active develop BOLTS but I would fix bugs to keep it as a usable add for FreeCAD. But this only makes sence if we use my repo with bug fixes.

bernd

**Comment by yorikvanhavre** [comment]
Yes maybe it's a better idea. The original BOLTS project seems a bit stalled (last commit > 1 year), so it seems a good idea to use your "built" version in freecad... I'll do the change

**Comment by berndhahnebach** [comment]
great, just tested, runs without any problems. See https://forum.freecadweb.org/viewtopic.php?f=8&t=4549&p=192787#p192787

bernd
