### ISSUE TITLE
New Workbench for possible inclusion

### ISSUE THREAD

**Issue by edwardvmills** [FreeCAD/FreeCAD-addons#39]
Hi yorik, Kunda1 suggested i propose this workbench here, and i think it is a good idea.

Of course, it's not really a finished product, but few things ever are. It can conceivably be useful to some people, so if you can, please include it in the addon manager.

Thank you,
Edward Mills

repo location:
https://github.com/edwardvmills/Silk

proposed Readme entry:

#### Silk
NURBS Surface modeling tools focused on low degree and seam continuity 

![Silk_Demo_02](https://github.com/edwardvmills/Silk/blob/master/Resources/Demo_files/Silk_Demo_02.png?raw=true)

**Comment by yorikvanhavre** [comment]
Closed together with #43
