### ISSUE TITLE
Please add Lattice2

### ISSUE THREAD

**Issue by DeepSOIC** [FreeCAD/FreeCAD-addons#4]
Hi, Yorik! (or whoever is reading this)
Can you please add [Lattice2](https://github.com/DeepSOIC/Lattice2) to this list?
Thanks.

I also think that Lattice1 should somehow be marked as deprecated.

**Comment by yorikvanhavre** [comment]
Done! I think you could add that in the description line of Lattice1 on github (that description line is what is fetched by the addons macro), because at the moment there is not much other way to mark something as deprecated on our side... apart from removing it of course.

**Comment by DeepSOIC** [comment]
Thanks!
