### ISSUE TITLE
Check for macro directory before symlinking

### ISSUE THREAD

**Issue by joha2** [FreeCAD/FreeCAD-addons#40]
Hi Yorik,

I tested the addon manager including it's new metadata functionality in my new freecad-daily installation on my Linux Mint. There is some small bug: The addon manager cannot finish the installation procedure if the macro directory not exists. For freecad-daily the macro directory is set to ~/.FreeCAD/Macro by default, but directly after installation this directory does not exist. Therefore the addon manager throws an exception letting the installation process in an undefined state. (And the user, too ;-) )

My suggestions:
* Either you may check whether the directory exists and if not mkdir it without any message
* Or you create a try block throwing a warning if the directory not exists

On the other hand when I mkdir the macro directory manually, the addon manager works perfect. :-)

Best wishes
Johannes

**Comment by yorikvanhavre** [comment]
done in FreeCAD/FreeCAD@cc8770677
