### ISSUE TITLE
repo is missing 'tags' (aka 'topics' in Github)

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-addons#42]
@yorikvanhavre i suggest we add 
`freecad` `addon` `workbench` etc...

**Comment by luzpaz** [comment]
This can be easily done. @yorikvanhavre if you give me access to the repo I will take care of little things like this.

**Comment by yorikvanhavre** [comment]
I added you there @luzpaz

**Comment by luzpaz** [comment]
Thanks! Added tags. Closing ticket
