### ISSUE TITLE
Request to add FreeCAD Manipulator Workbench

### ISSUE THREAD

**Issue by easyw** [FreeCAD/FreeCAD-addons#48]
Could I kindly request that the Manipulator workbench would be added?
https://github.com/easyw/Manipulator
This is an evolution of the Center Align Macro
[CenterAlignObjectswFacesEdges](https://github.com/easyw/FreeCAD_Macros/raw/master/Align%20Objects/CenterAlignObjectswFacesEdges.py)

reference at FreeCAD forum here
https://forum.freecadweb.org/viewtopic.php?f=22&t=18655&start=50#p193949
https://forum.freecadweb.org/viewtopic.php?f=9&t=24742

**Comment by luzpaz** [comment]
@yorikvanhavre this could be merged, I believe. What do you think?

**Comment by yorikvanhavre** [comment]
sure, done!
