### ISSUE TITLE
Cannot retrieve any add-ons - URL error

### ISSUE THREAD

**Issue by abudden** [FreeCAD/FreeCAD-addons#6]
I have just installed FreeCAD-addons by downloading from [the link shown in the readme file][https://github.com/FreeCAD/FreeCAD-addons/raw/master/addons_installer.FCMacro] and copying it to my user macro folder.  When I run the macro, it opens a window, downloads the list of addons and shows the list of addons.  When I select any addon in the list, it says "Retrieving info from <name>" where <name> depends on which entry I've clicked.  The Report view shows the following error:

```
Traceback (most recent call last):
  File "C:/al/insync/Metalwork/Drawings/FreeCADMacros/addons_installer.FCMacro", line 241, in run
    u = urllib2.urlopen(url)
  File "C:\applications\graphics\freecad\bin\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\applications\graphics\freecad\bin\lib\urllib2.py", line 396, in open
    protocol = req.get_type()
  File "C:\applications\graphics\freecad\bin\lib\urllib2.py", line 258, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: animation
```

This appears to be due to the way the URL is retrieved in the macro on line 239:

```python
            url = self.repos[self.idx][1]
```

I added a short line before line 241:

```python
            sys.stderr.write("Opening %s from %r\n" % (url, self.repos[self.idx]))
```

This gives:

```
Opening animation from ['animation @ fbeee84', 'animation', 0]
```

I suspect the second entry in that list should be a full URL, but although I think this is being created on line 207, I don't know enough about how it's supposed to work to know why it isn't!

Thanks for any help you can offer.

**Comment by yorikvanhavre** [comment]
this is now fixed.
