### ISSUE TITLE
Creating a symlink on windows requires admin rights

### ISSUE THREAD

**Issue by afester** [FreeCAD/FreeCAD-addons#61]
When installing the BOLTSFC module, I am getting

```Traceback (most recent call last):
  File ".../AppData/Roaming/FreeCAD/Macro/addons_installer.FCMacro", line 665, in run
    symlink(clonedir+os.sep+f, macrodir+os.sep+f)
  File ".../AppData/Roaming/FreeCAD/Macro/addons_installer.FCMacro", line 69, in symlink
    raise ctypes.WinError()
WindowsError: [Error 1314] A required privilege is not held by the client.
```

This is caused by a Windows Security Policy which restricts symbolic link creation to Administrators: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-vista/cc766301(v=ws.10)#create-symbolic-links

I suggest to copy the file instead of creating a symlink on windows.

Alternatively, could modules directly be installed into the "Macro" directory, including their sub directories? Why is it required to install into "Mods" and then create a symlink of the macro file into the "Macro" directory?

**Comment by luzpaz** [comment]
@sgrogan what do you think about #69 ? thanks

**Comment by sgrogan** [comment]
It should be good on Win10, I don't see a path to backwards compatibility onWin.

**Comment by luzpaz** [comment]
@sgrogan green light to merge the PR ?

**Comment by chennes** [comment]
This has been resolved by copying the macro if the symlink fails. A long-term solution is to make the macro Manager aware of multiple macro installation locations: that's on my to-do list, but it's not a priority right now.
