### ISSUE TITLE
Autoload, CommandPanel and SelectorToolbar

### ISSUE THREAD

**Issue by triplus** [FreeCAD/FreeCAD-addons#64]
Hi.

Some users requested it therefore i went over the list and noticed this modules are not yet included:

**Autoload:**
https://github.com/triplus/Autoload

**Command panel:**
https://github.com/triplus/CommandPanel

**Selector toolbar:**
https://github.com/triplus/SelectorToolbar

It would be nice if they could be added.

Thanks.

**Comment by luzpaz** [comment]
@yorikvanhavre this is a good idea to have before 0.17 is released

**Comment by yorikvanhavre** [comment]
Done with a23e2c48
