### ISSUE TITLE
Addon-Manager should show current version of addon installed and if there is an update (show pending update version)

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-addons#67]

**Comment by luzpaz** [comment]
> Show current version of addon in _About FreeCAD_ dialog  

@DeepSOIC do any of your WBs do this already ?

**Comment by DeepSOIC** [comment]
@luzpaz most likely - no. I am not quite an addon-wb expert here, though...

**Comment by luzpaz** [comment]
Thanks DeepSOIC,
Perhaps @realthunder has a solution ?

**Comment by realthunder** [comment]
I am not familiar with addon-manager either. But I know Stepup workbench by @easyw has the update notification function.

**Comment by luzpaz** [comment]
@realthunder apologies..i should really split this issue up in to 2 tickets. I'm more interested ATM in how to hook in version information of an installed addon in to the _About FreeCAD_ dialog

**Comment by chennes** [comment]
Now that we have version information in package.xml, this works as expected for displaying the current installed version. AddOns must be updated to include this metadata file, however. The same is true for showing the version of a pending update.
