### ISSUE TITLE
Add new Workbench : Work Feature workbench with parametric objects

### ISSUE THREAD

**Issue by Rentlau** [FreeCAD/FreeCAD-addons#70]
Hello,
Is there any value to add this workbench to /FreeCAD-addons ?
If yes feel free to do, i will be very please. 
Github is :
https://github.com/Rentlau/WorkFeature-WB
Thank you very much.
Rentlau_64

**Comment by luzpaz** [comment]
@Rentlau care to specify the forum thread this is discussed on?

**Comment by luzpaz** [comment]
Added in 2a0133d32a0028a9acd2e1d86a3503fd389e95db
