### ISSUE TITLE
Window too short

### ISSUE THREAD

**Issue by joelgraff** [FreeCAD/FreeCAD-addons#74]
When opening the addon manager, the window height is too short to be useful.   I suggest setting the default height to 2/3rd's the screen height.

**Comment by luzpaz** [comment]
QGIS does this:   
 
![image](https://user-images.githubusercontent.com/4140247/41916443-939cca32-7947-11e8-988c-e781276cfe3c.png)

**Comment by luzpaz** [comment]
@yorikvanhavre in 
https://github.com/FreeCAD/FreeCAD-addons/blob/master/addons_installer.FCMacro#L177
we see 
`self.resize(326, 304)`   
If I change that to
 `self.resize(626, 304)`  
would it make the Addon Manager widget wider ?

**Comment by yorikvanhavre** [comment]
yes

**Comment by luzpaz** [comment]
@joelgraff something like this? 

![image](https://i.imgur.com/oVBmq29.png)

ref: https://forum.freecadweb.org/viewtopic.php?f=34&t=20091&p=248217#p248217
