### ISSUE TITLE
No feedback after installing

### ISSUE THREAD

**Issue by joelgraff** [FreeCAD/FreeCAD-addons#75]
After installing an addon,  no feed back is given.  At a minimum,  just a message output to the report view would be useful: "addon [name] successfully installed."  Or perhaps refresh the list view to show the addon checked.

**Comment by sgrogan** [comment]
For FreeCAD addons-manager, I think it's fixed.
For the addons macro, I imagine it is deprecated and won't be fixed.

**Comment by luzpaz** [comment]
@sgrogan what do you mean by ?
>  For the addons macro, I imagine it is deprecated and won't be fixed.

**Comment by luzpaz** [comment]
PRs welcome

**Comment by luzpaz** [comment]
![addon_manager_status_update](https://user-images.githubusercontent.com/4140247/45246741-ec2b4300-b2d0-11e8-9289-0f4694c8a435.png)
Looks like we do get an indication that addon installed and prompted for us to restart FreeCAD

**Comment by luzpaz** [comment]
Now if the UI can give more emphasis with this information, that would be great. I'll open a separate issue for this.
