### ISSUE TITLE
Error when installing addons

### ISSUE THREAD

**Issue by russell** [FreeCAD/FreeCAD-addons#79]
Hey,

When trying to load a part the loading bar never completes, and I see the following error in the console.

This is on Linux using the AppImage install of FreeCAD 0.17 (13522)

![screenshot from 2018-05-27 10-54-15](https://user-images.githubusercontent.com/2660/40584133-5702f078-619c-11e8-8724-9ff1fbe1efa9.png)

```
Traceback (most recent call last):
  File "/home/russell/.FreeCAD/Macro/addons_installer.FCMacro", line 525, in run
    desc = re.findall("<meta content=\"(.*?)\" name",p)[4]
IndexError: list index out of range
```

**Comment by luzpaz** [comment]
@russell can you recreate with the latest appImage r13780 ?
https://github.com/FreeCAD/FreeCAD/releases/download/0.18_pre/FreeCAD_0.18.13780.glibc2.17-x86_64.AppImage

**Comment by luzpaz** [comment]
@russell  ping

**Comment by luzpaz** [comment]
No response from OP and no one else reporting a problem. Closing ticket for now

**Comment by russell** [comment]
Sorry for the late reply. Just tested it then.  Worked perfectly.

Thanks! :tada:
