### ISSUE TITLE
Add "AirPlaneDesign" add-on

### ISSUE THREAD

**Issue by Symbian9** [FreeCAD/FreeCAD-addons#83]
Add-on location:

- https://github.com/FredsFactory/FreeCAD_AirPlaneDesign

![FreeCAD AirPlaneDesign add-on](https://raw.githubusercontent.com/FredsFactory/FreeCAD_AirPlaneDesign/master/AirPlaneDesignWorkbench.png)

### Reference

- https://github.com/FredsFactory/FreeCAD_AirPlaneDesign/issues/1

**Comment by luzpaz** [comment]
@Symbian9 please open a thread on the forum to encourage testing your workbench. Also if you could provide documentation for users and perhaps a screencast to make the process of understanding how your workbench works, easier. Thanks!

**Comment by luzpaz** [comment]
@FredsFactory are you giving the green-light for submitting your WB to FreeCAD-addons ?

**Comment by FredsFactory** [comment]
Yes...

**Comment by FredsFactory** [comment]
Yes...

**Comment by FredsFactory** [comment]
Yes
Fred

Envoyé de mon iPhone

**Comment by luzpaz** [comment]
AirPlaneDesign can now be installed via the FreeCAD addon Manager
