### ISSUE TITLE
Geneva Mechanism Gui macro is cut off.

### ISSUE THREAD

**Issue by DieKatzchen** [FreeCAD/FreeCAD-addons#88]
Since the addon manager pulls from the wiki, and I don't have wiki access (and don't really need it), I can't do a pull request, but the full, correct macro is from [this post](https://forum.freecadweb.org/viewtopic.php?t=7756#p63483). I copied the missing part to the end of my local copy and it makes it work (after correcting indentation, of course). Can someone who has wiki access fix the code on the wiki?

**Comment by luzpaz** [comment]
Hey @galou can you look in to this since it's more a macro issue than a WB issue. Thanks!

**Comment by luzpaz** [comment]
@DieKatzchen I'm confused, what do you mean that the addon-manager pulls from the wiki?

**Comment by DieKatzchen** [comment]
While trying to figure out where the macro is stored, I found a thread describing how the manager pulls from the wiki instead of a git for various reasons. The version I get using the manager cuts off at the same point as on the wiki, so I assume it's still true.

**Comment by luzpaz** [comment]
@DieKatzchen do you mind retesting again ?

**Comment by luzpaz** [comment]
Should be fixed per https://forum.freecadweb.org/viewtopic.php?f=22&t=29701#p243683
Thanks for the report.

**Comment by DieKatzchen** [comment]
Can confirm working. Thanks.
