### ISSUE TITLE
Cura Engine relative path

### ISSUE THREAD

**Issue by Nemesis81** [FreeCAD/FreeCAD-addons#9]
As the repo point to cblt2l repo the plugin is unusable.
it should point to yorik repo https://github.com/yorikvanhavre/FreeCAD-CuraEngine-Plugin to solve this problem as cblt2l don't looks to be active on github nor on freecad forum.

**Comment by yorikvanhavre** [comment]
I would actually prefer that someone with more knowledge of cura would take this (fork my repo and become kind of "official" maintainer), because I'll be almost unable to solve any bug there...

**Comment by yorikvanhavre** [comment]
The change that was on my repo has been included in the original one, so there is no reason to use mine anymore... So I'm closing this
