### ISSUE TITLE
Revert b0f942c2 and remove exploded_animation correctly

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-addons#91]
Ref https://github.com/FreeCAD/FreeCAD-addons/issues/90#issuecomment-409587870

**Comment by luzpaz** [comment]
@yorikvanhavre what do you say we knock this issue out ? I defer to you on this one.

**Comment by luzpaz** [comment]
@yorikvanhavre no joy: 
```
[foo@bar FreeCAD-addons]$ git submodule add ExplodedAssembly https://github.com/JMG1/ExplodedAssembly.git
repo URL: 'ExplodedAssembly' must be absolute or begin with ./|../
```

**Comment by yorikvanhavre** [comment]
The correct syntax is the contrary:
`git submodule add https://github.com/JMG1/ExplodedAssembly.git ExplodedAssembly`
But I did it already: 6c01170
