### ISSUE TITLE
Tracking migration of FreeCAD workbenches to Py3/Qt5

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-addons#93]
Ref: https://forum.freecadweb.org/viewtopic.php?f=10&t=30624

**Comment by Rentlau** [comment]
WorkFeature **MACRO** is now compatible with py3 and QT5 FreeCAD versions.
Let me know if you detect any issue.

**Comment by chennes** [comment]
The remaining Addons on this list have been marked as "Python 2-only" and/or "Deprecated" (as requested by their author).
