### ISSUE TITLE
Feature: Auto-update addons

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-addons#94]
Addon Manager checking for updates of any addons and auto-update them + reporting that it has done so (and like Atom editor, prompting to restart FreeCAD if necessary)

**Comment by easyw** [comment]
The autoupdate could broke some production chain.
I would option for a notification and leave the update to the user.
Moreover, sometimes during the development process, an auto update could wipe the work in progress mod folder.

**Comment by luzpaz** [comment]
Good point. Will close this issue and re-formulate a variation of it.
