### ISSUE TITLE
Addon Manager notification should be more distinguishable

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-addons#97]
Right now notification from the Addon Manager are very muted and not conspicuous. For example as we see in #75 a screenshot when a workbench is downloaded the feedback is easy to miss:  

![addon_manager_status_update](https://user-images.githubusercontent.com/4140247/45246741-ec2b4300-b2d0-11e8-9289-0f4694c8a435.png)

Request: Distinguish notifications better.

**Comment by chennes** [comment]
The "Please restart" is now much "louder".
